services:
  pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    stdin_open: true
    tty: true

  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - "8888:8888"
    command: >
      bash -c "pip install --no-cache-dir jupyterlab==4.1.6 &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''"
